# ç«™ç‚¹åï¼šåŠŸèƒ½æ˜¯æŒ‡å®šç”Ÿæˆçš„ç«™ç‚¹çš„åç§°ã€‚
site_name: Air is Full | ğŸ¥°
# ç«™ç‚¹URLï¼šåŠŸèƒ½æ˜¯æŒ‡å®šç”Ÿæˆçš„ç«™ç‚¹çš„URLã€‚
site_url: https://linxinji.github.io/Air-is-Full/
# ç«™ç‚¹æè¿°ï¼šåŠŸèƒ½æ˜¯æŒ‡å®šç”Ÿæˆçš„ç«™ç‚¹çš„æè¿°ã€‚
site_description: Air is Full
# ç«™ç‚¹ç›®å½•ï¼šåŠŸèƒ½æ˜¯æŒ‡å®šç”Ÿæˆçš„ç«™ç‚¹çš„ç›®å½•ã€‚
site_dir: site

# ä»“åº“URLï¼šåŠŸèƒ½æ˜¯æŒ‡å®šç”Ÿæˆçš„ç«™ç‚¹çš„ä»“åº“URLã€‚
repo_name: Air is Full
repo_url: https://github.com/LinXinJi/Air-is-Full

# ç‰ˆæƒä¿¡æ¯
copyright: Copyright  &copy;  2026-2030  LinXinJi

# ä¸»é¢˜
theme:
  name: material
  language: zh
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  palette:
    # æµ…è‰²æ¨¡å¼
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # æ·±è‰²æ¨¡å¼
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.footer        # å¯ç”¨é¡µè„šå¯¼èˆª
    - navigation.tabs          # å¯ç”¨æ ‡ç­¾é¡µå¯¼èˆª
    - navigation.tabs.sticky   # å¯ç”¨æ ‡ç­¾é¡µå¯¼èˆªå›ºå®š
    - navigation.sections      # å¯ç”¨ç›®å½•é¡µå¯¼èˆª
    - navigation.instant       # å¯ç”¨å³æ—¶é¢„è§ˆ
    - navigation.path          # å¯ç”¨è·¯å¾„å¯¼èˆª
    - navigation.indexes       # å¯ç”¨ç´¢å¼•é¡µå¯¼èˆª
    - content.code             # ä»£ç é«˜äº®
    - navigation.top           # å¯¼èˆªæ ç½®é¡¶
    - navigation.sidebar       # å·¦ä¾§å¯¼èˆªï¼šä¿æŒé»˜è®¤å¼€å¯ï¼Œæ˜¾ç¤ºå…¨å±€å¯¼èˆªç»“æ„
    - toc.sidebar              # å³ä¾§ç›®å½•ï¼šå¯ç”¨å³ä¾§ TOC ä¾§è¾¹æ 
    - toc.follow               # è®©å³ä¾§ç›®å½•è·Ÿéšé¡µé¢æ»šåŠ¨é«˜äº®å½“å‰ä½ç½®:
    - content.tabs.link        # å¯ç”¨å†…å®¹æ ‡ç­¾é¡µé“¾æ¥
    - search.suggest           # å¯ç”¨æœç´¢å»ºè®®
    - content.code.copy        # ä»£ç å¤åˆ¶æŒ‰é’®
    - content.tooltips         # å†…å®¹æ‚¬æµ®æç¤º

# å¯¼èˆª
nav:
  - Home | ğŸ : 
    - index.md
  - Cultivation Between Realms | ğŸ¤—:
    - cultivation-between-realms/
  - Code on Farm | ğŸŒ±:
    - code-on-farm/
  - Fly in Air | â˜ï¸:
    - fly-in-air/
  - Walk to Heart | â¤ï¸:
    - walk-to-heart/
  - About | â„¹ï¸: 
    - about.md  

# é¡µè„š
extra:
  homepage: https://linxinji.github.io/Air-is-Full/
  generator: false
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/LinXinJi/Cultivation-Between-Realms
    - icon: fontawesome/solid/rss
      link: https://linxinji.github.io/Cultivation-Between-Realms/feed_rss_created.xml
    - icon: fontawesome/brands/discord
      link: https://discord.gg/9b23z6h
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/LinXinJi_
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/LinXinJi/

# æ’ä»¶
plugins: 
  - offline      # ç¦»çº¿æ¨¡å¼æ’ä»¶
  - search       # æœç´¢æ’ä»¶
  - multirepo:                                            # å¤šä»“åº“æ’ä»¶
      repos:
        - section: Cultivation Between Realms
          import_url: ./cultivation-between-realms
        - section: Code on Farm
          import_url: ./code-on-farm
        - section: Fly in Air
          import_url: ./fly-in-air  
        - section: Walk to Heart
          import_url: ./walk-to-heart

markdown_extensions:
  - pymdownx.superfences            # æ”¯æŒé«˜çº§ä»£ç å—
  - pymdownx.tabbed:                # æ ‡ç­¾é¡µ
      alternate_style: true  
  - pymdownx.highlight:             # ä»£ç é«˜äº®
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - abbr
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details

# é¢å¤–çš„CSSæ–‡ä»¶
extra_css:
  - css/fonts.css

# é¢å¤–çš„JSæ–‡ä»¶
extra_javascript:
  - js/extra.js